row = {
    "spend": 1,
    "impressions": 0,
    "clicks": 0,
    "purchases": 0,
    "link_clicks": 0,
    "adds_to_cart": 0,
    "ad_network_installs": 0,
    "actions_lead": 0,
    "actions_pixel_lead": 0,
    "ad_network_sessions": 0,
    "all_conversions": 0,
    "ad_account": 0,
    "ad_account_name": "test_adaccount",
    "campaign": "test_campaign",
    "campaign_id": 0,
    "adgroup": "test_adgroup",
    "adgroup_id": 0,
    "ad": "test_ad",
    "ad_id": 0,
    "country": "test_country",
    "ad_network": "test_adnetwork",
    "date": "2022-05-01"
}
