row = {
    'Spend': 1,
    'Impressions': 0,
    'Clicks': 0,
    'Purchases': 0,
    'Link clicks': 0,
    'Adds to cart': 0,
    'AdNetwork installs': 0,
    'Actions lead': 0,
    'Actions pixel lead': 0,
    'AdNetwork sessions': 0,
    'All conversions': 0,
    'AdAccount': 0,
    'AdAccount name': 'test_adaccount',
    'Ad campaign': 'test_campaign',
    'Ad campaign ID': 0,
    'Ad group': 'test_adgroup',
    'Ad group ID': 0,
    'Ad': 'test_ad',
    'Ad ID': 0,
    'Country': 'test_country',
    'Ad network': 'test_adnetwork',
    'Date': '2022-05-01',
}
